SELECT
    tr.NOME,
    dtr.QUANTIDADE,
    'Físico' as TIPO
FROM DOC_TIPORECURSO dtr
JOIN TIPORECURSOFISICO tr ON dtr.TIPORECURSOFISICO = tr.IDTIPORECURSO
WHERE dtr.DOCUMENTODEREQUISITO = %s

UNION ALL

SELECT
    rh.NOMEPROFISSAO,
    drh.QUANTIDADE,
    'Humano' as TIPO
FROM DOC_RH drh
JOIN RECURSOHUMANO rh ON drh.RECURSOHUMANO = rh.NOMEPROFISSAO
WHERE drh.DOCUMENTODEREQUISITO = %s;
