-- Lista pedidos com filtros opcionais.
SELECT
    p.IDPEDIDO,
    p.NOMEEVENTOPROPOSTO,
    p.STATUS,
    p.LOCALPROPOSTO,
    p.DATAINICIOPROPOSTO,
    p.DATAFIMPROPOSTO,
    p.DATASUBMISSAO,
    u.NOME AS NOME_USUARIO,
    a.NOME AS NOME_ANALISTA,
    g.NOME AS NOME_GERENTE,
    p.DESCRICAO
FROM PEDIDO p
JOIN USUARIO u ON p.USUARIO = u.NDOC
LEFT JOIN ANALISTA a ON p.ANALISTA = a.CPF
LEFT JOIN GERENTE g ON p.GERENTE = g.CPF
-- WHERE clauses are added dynamically in backend
