SELECT
    i.NROPATRIMONIO,
    i.STATUSITEM,
    i.QUALIDADE,
    i.TAMANHO,
    trf.NOME AS TIPORECURSOFISICO_NOME,
    a.IDARMAZEM AS ARMAZEM_ID,
    a.ENDERECO AS ARMAZEM_ENDERECO
FROM ITEM i
JOIN TIPORECURSOFISICO trf ON i.TIPORECURSOFISICO = trf.IDTIPORECURSO
LEFT JOIN ARMAZEM a ON i.ARMAZEM = a.IDARMAZEM;